version: '3.8'
services:
  rishabh-ui-app: # name of service 
    image: rishabh:webappv1 # name i want to build
    build: # location & name of dockerfile
      context: .
      dockerfile: rishabhday4app.dockerfile
    container_name: rishabhc1 # after image build the container i want to create
    ports: # port forwarding
    - 1836:80
